### ISSUE TITLE
Raise error if profile not found in config file

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#135]
The feedback from constructor is not helpful if you request a profile that is not found.

This is because `config/constructor.py` defaults to a blank config (with empty manager/services/user_profile entries) if a nonexistant profile is requested. This results in unexpected behavior. Instead, we should just raise a KeyError with a helpful message.

Additionally, maybe `datafs configure list`, a command which could list available profiles, would be useful to include in the full list of proposed configure commands in #54 

```
$ datafs --profile nonexistant_profile list
Traceback (most recent call last):
  File "c:\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda2\Scripts\datafs.exe\__main__.py", line 9, in <module>
  File "c:\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\anaconda2\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\anaconda2\lib\site-packages\datafs\datafs.py", line 349, in list
    _generate_api(ctx)
  File "c:\anaconda2\lib\site-packages\datafs\datafs.py", line 58, in _generate_api
    requirements=ctx.obj.requirements)
  File "c:\anaconda2\lib\site-packages\datafs\config\helpers.py", line 136, in get_api
    APIConstructor.attach_manager_from_config(api, profile_config)
  File "c:\anaconda2\lib\site-packages\datafs\config\constructor.py", line 41, in attach_manager_from_config
    manager = cls._generate_manager(config['manager'])
  File "c:\anaconda2\lib\site-packages\datafs\config\constructor.py", line 126, in _generate_manager
    'Manager not fully specified. Give '
ValueError: Manager not fully specified. Give "class:manager_name", e.g. "class:MongoDBManager".
```

**Comment by delgadom** [comment]
Closed by #149
