### ISSUE TITLE
Check archive names before creation

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#235]
We should try to find a way of ensuring that an archive name is valid before allowing it to be created.

For example:

```python
>>> import datafs
>>> api = datafs.get_api('test')
>>> archive = api.create('\\\\\\C::\\\~~~~~!!$@')
>>> archive
<DataArchive auth://\\\C::\\~~~~~!!$@>
>>> with archive.open('w+') as f:
...   f.write(u'the file contents')
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\envs\datafs\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Anaconda2\envs\datafs\lib\site-packages\datafs\core\data_archive.py", line 450, in open
    with opener as f:
  File "C:\Anaconda2\envs\datafs\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Anaconda2\envs\datafs\lib\site-packages\datafs\core\data_file.py", line 183, in open_file
    authority, cache, read_path, version_check, hasher) as read_fs:
  File "C:\Anaconda2\envs\datafs\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Anaconda2\envs\datafs\lib\site-packages\datafs\core\data_file.py", line 75, in _choose_read_fs
    if not authority.fs.isfile(read_path):
  File "C:\Anaconda2\envs\datafs\lib\site-packages\fs\errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "C:\Anaconda2\envs\datafs\lib\site-packages\fs\osfs\__init__.py", line 258, in isfile
    return _isfile(self.getsyspath(path))
  File "C:\Anaconda2\envs\datafs\lib\site-packages\fs\osfs\__init__.py", line 166, in getsyspath
    self.validatepath(path)
  File "C:\Anaconda2\envs\datafs\lib\site-packages\fs\base.py", line 305, in validatepath
    raise InvalidCharsInPathError(path)
fs.errors.InvalidCharsInPathError: Path contains invalid characters: \\\C::\\~~~~~!!$@/None
>>>
```

**Comment by jgerardsimcock** [comment]
Definitely need to do this
