### ISSUE TITLE
We don't build with moto 1.0.0

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#294]
Travis fails for pyup's moto 1.0.0 PR. Looks like a significant issue where we are trying to connect directly to boto (bypassing moto). Maybe an import or specification/monkeypatching issue.

Either way, this only affects tests, as moto isn't used in the core package, so put this down as a like-to-fix.

**Comment by delgadom** [comment]
Something in the moto/boto interface appears to be causing all tests to fail!

see, e.g. https://travis-ci.org/ClimateImpactLab/DataFS/jobs/249318177

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/_pytest/config.py", line 373, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 215, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/travis/build/ClimateImpactLab/DataFS/tests/conftest.py", line 7, in <module>
    import moto
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/__init__.py", line 8, in <module>
    from .apigateway import mock_apigateway  # flake8: noqa
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/apigateway/__init__.py", line 2, in <module>
    from .models import apigateway_backends
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/apigateway/models.py", line 7, in <module>
    from moto.core import BaseBackend
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/core/__init__.py", line 2, in <module>
    from .models import BaseBackend  # flake8: noqa
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/core/models.py", line 8, in <module>
    from .responses import metadata_response
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/moto/core/responses.py", line 8, in <module>
    from boto.exception import JSONResponseError
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
ERROR: could not load /home/travis/build/ClimateImpactLab/DataFS/tests/conftest.py
```

**Comment by delgadom** [comment]
This looks relevant https://github.com/travis-ci/travis-ci/issues/7940
